trigger: none
pr: none

pool: Kubernetes Pool

variables:
  - group: cluster-api-image-builder-variables

parameters:
  - name: imagesToBuild
    type: object
    default:
      - name: ubuntu-2004
        k8sVersion: "1.23.4"
        os: Ubuntu
        osVersion: 2004

stages:
  - ${{ each build in parameters.imagesToBuild }}:
      - template: /deploy/stages/build-capi-skus.yaml
        parameters:
          BUILD_POOL: Kubernetes Pool
          CONTAINER_IMAGE: "loclcorp.azurecr.io/image-builder:foodx-v0.1.11" # Dev container image URL to use. Should have Azure CLI, Packer and Ansible.
          AZURE_TENANT_ID_VHD: $( tenant-id ) # tenant ID to build the vhd
          AZURE_CLIENT_ID_VHD: $( acr-serviceprincipal-id ) # Service principal ID to build the vhd
          AZURE_CLIENT_SECRET_VHD: $( acr-serviceprincipal-password ) # Service principal secret to build the vhd
          AZURE_SUBSCRIPTION_ID_VHD: $( subscription-id-corp-locl-prd ) # Subscription ID to build the vhd
          AZURE_TENANT_ID_SKU: $( tenant-id ) # tenant ID to PUT the SKU
          AZURE_CLIENT_ID_SKU: $( acr-serviceprincipal-id ) # Service principal ID to PUT the SKU
          AZURE_CLIENT_SECRET_SKU: $( acr-serviceprincipal-password ) # Service principal secret to PUT the SKU
          PUBLISHER: foodx-technologies # the name of the publisher to create the sku for
          OFFER: capi # the name of the offer to create the sku for
          SKU_TEMPLATE_FILE: /images/capi/packer/azure/sku-template.json # the base template file to use for the sku
          KUBERNETES_VERSION: ${{ build.k8sVersion }}
          OS: ${{ build.os }}
          OS_VERSION: ${{ build.osVersion }}
